version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres
    django:
        build: .
        container_name: django
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - .:/var/www
        ports:
            - 80:8000
        depends_on:
            - postgres
