version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres:/var/lib/postgresql/data
    django:
        build:
            context: .
            dockerfile: library_back/Dockerfile
        container_name: django
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - .:/var/www
        ports:
            - 80:8000
        depends_on:
            - postgres
    react:
        build:
            context: .
            dockerfile: library_front/Dockerfile
        container_name: react
        depends_on:
            - django
        ports:
            - 3000:3000

volumes:
    postgres:
