version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres:/var/lib/postgresql/data
    django:
        build:
            context: library_back
            dockerfile: Dockerfile
        container_name: django
        command: run-back django-debug
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
        depends_on:
            - postgres
        ports:
            - 5000:8000
        volumes:
            - .:/var/www
            - static_django:/var/www/library_back/static
    react:
        build:
            context: library_front
            dockerfile: Dockerfile
        container_name: react
        depends_on:
            - django
        ports:
            - 3000:3000
    nginx:
        build:
            context: .
            dockerfile: library_nginx/Dockerfile
        container_name: nginx
        depends_on:
            - django
            - react
        ports:
            - 80:80
        volumes:
            - static_django:/var/www/library_back/static

volumes:
    postgres:
    static_django:
