name: Back CI Pipeline

on: push

jobs:
  linter:
    name: run / linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8 linter
        run: |
          flake8 --max-line-length=200 library_back/

  build:
    name: run / build
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build . -f library_back/Dockerfile -t back/django:$GITHUB_SHA
          docker save -o docker_image_$GITHUB_SHA back/django:$GITHUB_SHA
      - name: Caching image
        uses: actions/cache@v3
        with:
          key: library_back
          path: docker_image_${{ github.sha }}

  test:
    name: test / unity
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Restoring cached image
        uses: actions/cache@v3
        with:
          key: library_back
          path: docker_image_${{ github.sha }}
      - name: Running django container
        env:
          IMAGE_BACK: back/django:${{ github.sha }}
        run: |
          cp library_back/.env-sample library_back/.env
          docker load -i docker_image_$GITHUB_SHA
          docker-compose -f docker-compose.ci.yml -p back_$GITHUB_SHA up --no-build -d django
      - name: Running django tests
        run: |
          docker exec back_${{ github.sha }}_django_1 pytest library_back
