name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: deploy / backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Heroku push
        run: |
          git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git main
