name: Front CI Pipeline

on: push

jobs:
  linter:
    name: run / linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Installing ESLint
        working-directory: ./library_front
        run: |
          npm install eslint
      - name: Run ESLint linter
        working-directory: ./library_front
        run: |
          npx eslint src/
